#Shift Alt vim keys to switch windows

bind -n M-H previous-window
bind -n M-L next-window


#Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


# set vi-mode
set-window-option -g mode-keys vi
#Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Resize Panes
bind-key -r -T prefix       C-K              resize-pane -U 5
bind-key -r -T prefix       C-J 			 resize-pane -D 5
bind-key -r -T prefix       C-H				  resize-pane -L 5
bind-key -r -T prefix       C-L 			resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R

set -g mouse on
set-option -g mouse on



set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tmux-sensible' 
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank' 

run '~/.tmux/plugins/tpm/tpm'
